
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
        environment:
          GOPATH: /go
    steps:
      - run:
          name: create folder structure
          command: mkdir -p /go/src/github.com/pbaettig/promscriptsgw
      - checkout:
          path: /go/src/github.com/pbaettig/promscriptsgw
      - restore_cache:
          keys:
            - logrus-{{ checksum "/go/pkg/linux_amd64/github.com/sirupsen/logrus.a" }}
      
      - restore_cache:
          keys:
            - prometheus-{{ checksum "/go/pkg/linux_amd64/github.com/prometheus/client_golang/prometheus.a" }}
      - run: env
      - run:
          name: install dependencies
          command: |
            go get -v github.com/sirupsen/logrus \
            github.com/prometheus/client_golang/prometheus/promhttp \
            github.com/prometheus/client_golang/prometheus \
            github.com/konsorten/go-windows-terminal-sequences
  
      - run:
          name: update version in source
          command: sed -r -i "s/version = \".+\"/version = \"${CIRCLE_SHA1:0:7}\"/g" /go/src/github.com/pbaettig/promscriptsgw/cmd/promscriptsgw/version.go
      
      - run:
          name: Build linux binaries
          command: go build -o promscriptsgw_linux_amd64 /go/src/github.com/pbaettig/promscriptsgw/cmd/promscriptsgw/*.go
          environment:
            GOOS: linux
            GOARCH: amd64
      - run:
          name:  build OSX binaries 
          command: go build -o promscriptsgw_darwin_amd64 /go/src/github.com/pbaettig/promscriptsgw/cmd/promscriptsgw/*.go
          environment:
            GOOS: darwin
            GOARCH: amd64
      - run:
          name: build windows binaries
          command: go build -o promscriptsgw_windows_amd64 /go/src/github.com/pbaettig/promscriptsgw/cmd/promscriptsgw/*.go
          environment:
            GOOS: windows
            GOARCH: amd64
      
      - persist_to_workspace:
          root: .
          paths:
            - promscriptsgw_*
            - .circleci/publish_github_release.sh

      - save_cache: 
          key: logrus-{{ checksum "/go/pkg/linux_amd64/github.com/sirupsen/logrus.a" }}
          paths:
            - /go/pkg/linux_amd64/github.com/sirupsen
      
      - save_cache:
          key: prometheus-{{ checksum "/go/pkg/linux_amd64/github.com/prometheus/client_golang/prometheus.a" }}
          paths:
            - /go/pkg/linux_amd64/github.com/prometheus/client_golang/
  publish:
    docker:
      - image: circleci/golang:1.12 # because it has curl
    steps:
      - run:
          name: create workspace folder
          command: mkdir /tmp/ws
      - attach_workspace:
          at: /tmp/ws
      - run:
          name: list workspace
          command: ls -lah /tmp/ws

      - run:
          name: Create GitHub Release
          command: bash /tmp/ws/publish_github_release.sh
          environment:
            DRAFT: "true"
            FILES: "/tmp/ws/promscriptsgw_*"
            RELEASE_BODY: "This release was created automatically by CircleCI"
    

workflows:
  version: 2
  build-workflow:
    jobs:
      - build
      - publish:
          requires:
            - build
      #     filters:
      #       tags:
      #         only: /^v.*/
      #       branches:
      #         ignore: /.*/
