
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
        environment:
          GOPATH: /go
    steps:
      - run:
          name: create folder structure
          command: mkdir -p /go/src/github.com/pbaettig/promscriptsgw
      
      - checkout:
          path: /go/src/github.com/pbaettig/promscriptsgw

      - restore_cache:
          keys:
            - go-packages-{{ checksum "/go/src/github.com/pbaettig/promscriptsgw/.circleci/go_packages" }}

      - run: env
      
      - run:
          name: install dependencies
          working_directory: /go/src/github.com/pbaettig/promscriptsgw
          command: |
            grep -v '^#' <.circleci/go_packages | xargs go get -v 
  
      - run:
          name: update version in source
          working_directory: /go/src/github.com/pbaettig/promscriptsgw
          command: sed -r -i "s/version = \".+\"/version = \"${CIRCLE_SHA1:0:7}\"/g" cmd/promscriptsgw/version.go
      
      - run:
          name: build linux binaries
          working_directory: /go/src/github.com/pbaettig/promscriptsgw/cmd/promscriptsgw
          command: go build -o promscriptsgw_linux_amd64 *.go
          environment:
            GOOS: linux
            GOARCH: amd64
      
      - run:
          name:  build OSX binaries 
          working_directory: /go/src/github.com/pbaettig/promscriptsgw/cmd/promscriptsgw
          command: go build -o promscriptsgw_darwin_amd64 *.go
          environment:
            GOOS: darwin
            GOARCH: amd64
      
      - run:
          name: build windows binaries
          working_directory: /go/src/github.com/pbaettig/promscriptsgw/cmd/promscriptsgw
          command: go build -o promscriptsgw_windows_amd64 *.go
          environment:
            GOOS: windows
            GOARCH: amd64
      
      - run:
          name: copy binaries to workspace
          working_directory: /go/src/github.com/pbaettig/promscriptsgw/cmd/promscriptsgw
          command: cp promscriptsgw_* /home/circleci

      - run:
          name: copy GitHub release script
          working_directory: /go/src/github.com/pbaettig/promscriptsgw
          command: cp .circleci/publish_github_release.sh /home/circleci/
    
      - persist_to_workspace:
          root: /home/circleci
          paths:
            # persist built binaries to workspace
            - promscriptsgw_*
            - publish_github_release.sh

      - save_cache: 
          key: go-packages-{{ checksum "/go/src/github.com/pbaettig/promscriptsgw/.circleci/go_packages" }}
          paths:
            - /go/pkg

  publish:
    docker:
      - image: circleci/golang:1.12 # because it has curl
    steps:
      - run:
          name: create workspace folder
          command: mkdir /tmp/ws
      - attach_workspace:
          at: /tmp/ws
      - run:
          name: list workspace
          command: ls -lah /tmp/ws

      - run:
          name: Create GitHub Release
          command: bash /tmp/ws/publish_github_release.sh
          environment:
            DRAFT: "true"
            FILES: "/tmp/ws/promscriptsgw_*"
            RELEASE_BODY: "This release was created automatically by CircleCI"
    

workflows:
  version: 2
  build-workflow:
    jobs:
      - build
      - publish:
          requires:
            - build
      #     filters:
      #       tags:
      #         only: /^v.*/
      #       branches:
      #         ignore: /.*/
