
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
        environment:
          GOPATH: /go
    steps:
      - run: mkdir -p /go/src/github.com/pbaettig/promscriptsgw
      - checkout:
          path: /go/src/github.com/pbaettig/promscriptsgw
      - restore_cache:
          keys:
            - logrus-{{ checksum "/go/pkg/linux_amd64/github.com/sirupsen/logrus.a" }}
      
      - restore_cache:
          keys:
            - prometheus-{{ checksum "/go/pkg/linux_amd64/github.com/prometheus/client_golang/prometheus.a" }}

      - run: go get -v github.com/sirupsen/logrus github.com/prometheus/client_golang/prometheus/promhttp github.com/prometheus/client_golang/prometheus
      - run: pwd; ls -lah
      - run: sed -r -i "s/version = \".+\"/version = \"${CIRCLE_SHA1}\"/g" /go/src/github.com/pbaettig/promscriptsgw/cmd/promscriptsgw/version.go
      
      - run: go build -o promscriptsgw /go/src/github.com/pbaettig/promscriptsgw/cmd/promscriptsgw/*.go

      - save_cache: 
          key: logrus-{{ checksum "/go/pkg/linux_amd64/github.com/sirupsen/logrus.a" }}
          paths:
            - /go/pkg/linux_amd64/github.com/sirupsen
      
      - save_cache:
          key: prometheus-{{ checksum "/go/pkg/linux_amd64/github.com/prometheus/client_golang/prometheus.a" }}
          paths:
            - /go/pkg/linux_amd64/github.com/prometheus/client_golang/

workflows:
  version: 2
  build-workflow:
    jobs:
      - build
